---
defaults: &defaults
  redis:
    host: localhost
    port: 6379
  admin:
    username: '123'
    password: '123'
development:
  <<: *defaults
  staging: production
test:
  <<: *defaults
  staging: production
production:
  <<: *defaults
  staging: production

