---
defaults: &defaults
  redis:
    host: localhost
    port: 6379
development:
  <<: *defaults
  staging: production
test:
  <<: *defaults
  staging: production
production:
  <<: *defaults
  staging: production

